name: Automation Workflow

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  run-automation-test:
    runs-on: ubuntu-latest

    steps:
      # download repo
      - uses: actions/checkout@v3

      # setup java
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      # install chrome browser
      - name: Setup Chrome
        uses: browser-actions/setup-chrome@v2.1.0

      # setup graldew
      - name: Setup gradlew
        run: chmod +x gradlew

      # Execute gradlew command to run test
      - name: Execute Web Test
        run: ./gradlew web

      - name: Execute Api Test
        if: ${{ always() }}
        run: ./gradlew api
      
      # Archive Test Result
      - name: Archive Test Result
        uses: actions/upload-artifact@v5.0.0
        if: always()
        with:
          name: Cucumber Report
          path: reports
          
      # Deploy to Github pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4.0.0
        if: always()
        with:
          # Set a personal access token for pushing to the remote branch.
          github_token: ${{ secrets.GITHUB_TOKEN }}
          # Set an input directory for deployment.
          publish_dir: ./reports
